### ISSUE TITLE
:tongue: create a deposit page :1st_place_medal: 

### ISSUE THREAD

**Issue by TechInnovatorsHub** [TechInnovatorsHub/indices-trade-lab#11]
###  Tasks ;
As part of enhancing our financial services, we need to create a deposit page on our website.
The deposit page will allow users to securely and conveniently deposit funds into their accounts. The page should provide clear instructions, multiple deposit methods, and a seamless user experience.
It should also include necessary validation checks and error handling to ensure accurate and reliable transactions. 
The goal of this issue is to design and develop a robust deposit page that meets the needs of our users and aligns with our branding guidelines.

### Screenshot.
![deposit](https://github.com/TechInnovatorsHub/indices-trade-lab/assets/137064002/57776f94-3149-4a68-81b6-5762bff08023)

### Design.
[figma link](https://www.figma.com/proto/8QDTAOsCdSNaakq2Ec49ih/Untitled?node-id=126-12&source=email_invite&starting-point-node-id=3%3A2&scaling=contain).

### Steps;
**git branch deposit-page** to create your own branch
**git switch deposit-page**
**git pull origin main
npm run dev**
commit your changes and push to your github account
Lastly make a **PR** of your branch in your own Github account to the main branch of [indices-trade-lab](https://github.com/TechInnovatorsHub/indices-trade-lab)  repo in TechInnovatorsHub .

**Comment by KubasuIvanSakwa** [comment]
Can I be assigned to this page
