### ISSUE TITLE
:game_die: create a withdrawals page :racing_car: 

### ISSUE THREAD

**Issue by TechInnovatorsHub** [TechInnovatorsHub/indices-trade-lab#13]
###  Tasks ;
To provide our users with the ability to withdraw funds from their accounts, we need to create a dedicated withdrawal page. 
The withdrawal page should allow users to request and process withdrawals smoothly, ensuring the security of their transactions. It should incorporate appropriate security measures, verification steps, and transaction history tracking. 
The objective of this issue is to design and implement a user-friendly withdrawal page that ensures a seamless and reliable withdrawal experience for our users.

### Screenshot.
![withdrawals](https://github.com/TechInnovatorsHub/indices-trade-lab/assets/137064002/9054eea7-16db-4885-81e4-b792cd2ed82b)

### Design.
[figma link](https://www.figma.com/proto/8QDTAOsCdSNaakq2Ec49ih/Untitled?node-id=3-2&source=email_invite&starting-point-node-id=3%3A2&scaling=contain).

### Steps;
**git branch withdrawals-page** to create your own branch
**git switch withdrawals-page**
**git pull origin main
npm run dev**
commit your changes and push to your github account
Lastly make a **PR** of your branch in your own Github account to the main branch of [indices-trade-lab](https://github.com/TechInnovatorsHub/indices-trade-lab)  repo in TechInnovatorsHub .

**Comment by Serem-manu** [comment]
Started working on it

**Comment by Serem-manu** [comment]
done

**Comment by Serem-manu** [comment]
[issue 13](https://github.com/TechInnovatorsHub/indices-trade-lab/issues/13) completed
