### ISSUE TITLE
:+1: create a landing page :100: 

### ISSUE THREAD

**Issue by TechInnovatorsHub** [TechInnovatorsHub/indices-trade-lab#16]
###  Tasks ;
Create a clear and impressive landing page as per screenshot below.
The page should be responsive, optimized for various devices and screen sizes, and adhere to best practices for user experience and conversion rate optimization. The goal of this issue is to design a captivating landing page that captivates visitors, communicates our brand message, and entices them to take the next steps.

###Other tasks.
Make sure you complete on the works page.
by navigating to; [works](http://localhost:5173/works) or http://localhost:5173/works
Add the images and adjust the css of the second div.

### Screenshot.
![landing](https://github.com/TechInnovatorsHub/indices-trade-lab/assets/137064002/721870f3-896c-42b4-aa1d-4910ed1bb38c)

### Steps
**git branch landing-page** to create your own branch
**git switch landing-page**
**git pull origin main
npm run dev**
commit your changes and push to your github account
Lastly make a PR of your branch in your own Github account to the main branch of [indices-trade-lab](https://github.com/TechInnovatorsHub/indices-trade-lab) repo in TechInnovatorsHub .

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.
