### ISSUE TITLE
:tada: create a FAQs page :art: 

### ISSUE THREAD

**Issue by TechInnovatorsHub** [TechInnovatorsHub/indices-trade-lab#2]
This task has been assigned to [Ian Kale](https://github.com/kaleian).

###  Tasks ;
Create an FAQs page as per screenshot below.
Implement an intuitive navigation structure that allows users to easily find and access the desired questions and answers.
Format the FAQs page in a visually appealing and user-friendly manner.

### Screenshot.#1 
![faqs](https://github.com/TechInnovatorsHub/indices-trade-lab/assets/137064002/5ff3a010-33d4-4486-a46d-4d887369b9d4)

### Steps
Create a fork .
Clone the repo to your machine.
npm install
**npm run dev** to start the server
**git branch faq-page** to create your own branch
git switch faq-page
commit your changes and push to your github account
Lastly make a PR of your branch in your own Github account to the main branch of [indices-trade-lab](https://github.com/TechInnovatorsHub/indices-trade-lab)  repo in TechInnovatorsHub .

**Comment by kaleian** [comment]
started working on this issues 🔥
