### ISSUE TITLE
:tada: create a plans page :100: 

### ISSUE THREAD

**Issue by TechInnovatorsHub** [TechInnovatorsHub/indices-trade-lab#3]
This task has been assigned to [Lenox Isindu](https://github.com/lenox-isindu).

###  Tasks ;
Create an Plans page as per screenshot below.
Implement an intuitive navigation structure that allows users to easily find and access the desired questions and answers.
Format the Plans page in a visually appealing and user-friendly manner.

### Screenshot.#1 
![plans](https://github.com/TechInnovatorsHub/indices-trade-lab/assets/137064002/ec5810bb-9327-47e2-8134-47e7900fe71b)

### Steps
Create a fork .
Clone the repo to your machine.
npm install
**npm run dev** to start the server
**git branch plans-page** to create your own branch
**git switch plans-page**
commit your changes and push to your github account
Lastly make a **PR** of your branch in your own Github account to the main branch of [indices-trade-lab](https://github.com/TechInnovatorsHub/indices-trade-lab)  repo in TechInnovatorsHub .

**Comment by lenox-isindu** [comment]
I will work on this [🎉 create a plans page 💯](https://github.com/TechInnovatorsHub/indices-trade-lab/issues/3)

**Comment by TechInnovatorsHub** [comment]
:congratulations: well Done @lenox-isindu :100:
