### ISSUE TITLE
:tada: create customer support page :+1: 

### ISSUE THREAD

**Issue by TechInnovatorsHub** [TechInnovatorsHub/indices-trade-lab#4]
This task has been assigned to [Ivan Kubasu](https://github.com/KubasuIvanSakwa).

###  Tasks ;
Create an Plans page as per screenshot below.
Implement an intuitive navigation structure that allows users to easily find and access the desired questions and answers.
Format the Customer support page in a visually appealing and user-friendly manner.

### Screenshot.#1 
![support](https://github.com/TechInnovatorsHub/indices-trade-lab/assets/137064002/c1f64ac5-1e21-468d-89a9-7a3278ae5439)

### Steps;

Create a fork .
Clone the repo to your machine.
npm install
**npm run dev** to start the server
**git branch support-page** to create your own branch
**git switch support-page**
commit your changes and push to your github account
Lastly make a **PR** of your branch in your own Github account to the main branch of [indices-trade-lab](https://github.com/TechInnovatorsHub/indices-trade-lab)  repo in TechInnovatorsHub .

**Comment by KubasuIvanSakwa** [comment]
started on the customer support page

**Comment by TechInnovatorsHub** [comment]
Great :+1: Ivan make sure to create a fork.

**Comment by TechInnovatorsHub** [comment]
Done Successfully
