### ISSUE TITLE
:tada: create about us page :boom: 

### ISSUE THREAD

**Issue by TechInnovatorsHub** [TechInnovatorsHub/indices-trade-lab#5]
This task has been assigned to [Emmanuel Serem](https://github.com/Serem-manu).

###  Tasks ;
Create an about us page as per screenshot below.
Select and edit suitable images or graphics that visually enhance the page and align with our brand identity.
Center the title **about us**.
### Screenshot.
![about-us](https://github.com/TechInnovatorsHub/indices-trade-lab/assets/137064002/c700709a-7981-41a9-bde0-2a8fdba8968b)

### Steps;
Create a fork .
Clone the repo to your machine.
npm install
**npm run dev** to start the server
**git branch about-page** to create your own branch
**git switch about-page**
commit your changes and push to your github account
Lastly make a **PR** of your branch in your own Github account to the main branch of [indices-trade-lab](https://github.com/TechInnovatorsHub/indices-trade-lab)  repo in TechInnovatorsHub .

**Comment by Serem-manu** [comment]
I have started working on this
