### ISSUE TITLE
:tada: create how it works page :rotating_light:

### ISSUE THREAD

**Issue by TechInnovatorsHub** [TechInnovatorsHub/indices-trade-lab#6]
This task has been assigned to [Abel Ronoh](https://github.com/Abel-Ronoh).

###  Tasks ;
Create how it works page as per screenshot below.
Select and edit suitable images or graphics that visually enhance the page and align with our brand identity.
### Screenshot.
![how-it-works](https://github.com/TechInnovatorsHub/indices-trade-lab/assets/137064002/6b0e88e7-182b-4b29-8439-616e4e545c5a)

### Steps;
Create a fork .
Clone the repo to your machine.
npm install
**npm run dev** to start the server
**git branch works-page** to create your own branch
**git switch works-page**
commit your changes and push to your github account
Lastly make a **PR** of your branch in your own Github account to the main branch of [indices-trade-lab](https://github.com/TechInnovatorsHub/indices-trade-lab)  repo in TechInnovatorsHub .

**Comment by Abel-Ronoh** [comment]
have started working on this
